[versions]
activity-compose = "1.8.2"
accompanist-flowlayout = "0.32.0"
accompanist-pager = "0.28.0"
accompanist-permissions = "0.23.1"
accompanist-systemuicontroller = "0.31.6-rc"
androidx-junit = "1.1.5"
androidx-media3-ui = "1.2.0-rc01"
coil-compose = "2.4.0"
constraintlayout-compose = "1.0.1"
youtube-player-core-version = "12.1.0"
core-ktx = "1.12.0"
core-splashscreen = "1.1.0-alpha02"
datastore = "1.0.0"
espresso-core = "3.5.1"
facebook-android-sdk = "12.1.0"
facebook-login = "14.1.0"
firebase-analytics = "21.5.1"
firebase-auth-ktx = "22.3.1"
firebase-crashlytics = "18.6.2"
firebase-database = "20.3.0"
firebase-messaging = "23.4.1"
hilt-android-compiler = "2.48"
junit = "4.13.2"
kotlin-youtubeExtractor = "0.0.7"
kotlinx-serialization-json = "1.5.1"
lifecycle-runtime-ktx = "2.7.0"
bom = "2024.02.00"
hilt-version = "2.48"
hilt-compiler-version  ="2.44"
lottie = "6.1.0"
material-icons-extended = "1.6.1"
media3-exoplayer = "1.2.0-rc01"
media3-ui = "1.2.1"
nav_compose_version = "1.1.0"
hilt-work-version = "1.0.0"
lifecycle-viewmodel-ktx = "2.7.0"
paging-runtime-ktx = "3.2.1"
play-services-auth = "20.7.0"
protobuf-javalite = "3.21.9"
room-runtime = "2.5.0"
startup-runtime = "1.1.1"
timber_version = "5.0.1"
work-runtime-ktx = "2.8.1"
android-gradle = "8.2.2"
koltin = "1.9.10"
kotlin-serialize = "1.9.21"
google-service-version = "4.4.1"
chaquopy-version = "15.0.0"
protobuf-version = "0.9.1"
crashlytics = "2.9.9"
gradle-tool = "7.3.1"
material3-version = "1.2.0-alpha05"
retrofit-version = "2.9.0"
okhttp-version = "5.0.0-alpha.3"
scalar-converter-version = "2.9.0"
kotlin-serialization-version = "1.5.1"
jakewharton-convertor-version = "1.0.0"

[libraries]
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist-flowlayout" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-pager" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist-pager" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-ui" }
androidx-media3-exoplayer-v120rc01 = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3-ui" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3-ui" }
androidx-media3-ui-v120rc01 = { module = "androidx.media3:media3-ui", version.ref = "androidx-media3-ui" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-runtime-ktx" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging-runtime-ktx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room-runtime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup-runtime" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
youtube-player-core = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "youtube-player-core-version" }
facebook-android-sdk = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebook-android-sdk" }
facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebook-login" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebase-auth-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebase-database" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-messaging" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebase-database" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android-compiler" }
kotlin-youtubeExtractor = { module = "com.github.maxrave-dev:kotlin-youtubeExtractor", version.ref = "kotlin-youtubeExtractor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf-javalite" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf-javalite" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber_version" }

retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit-version" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp-version" }
scalar-converter = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "scalar-converter-version" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization-version" }
jakewharton-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "jakewharton-convertor-version" }

dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt-version" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-compiler-version" }
dagger_nav_compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "nav_compose_version"}
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-work-version" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work-version" }


compose-bom = { module = "androidx.compose:compose-bom", version.ref = "bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3-version" }


#test
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
compose-junit = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

gradle =  { module = "com.android.tools.build:gradle", version.ref = "gradle-tool" }

[bundles]
compose = [ "compose-ui", "compose-ui-graphics", "compose-ui-preview" ]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "koltin" }
android-dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version" }
android-kotlin-serialize = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialize" }
google-service = { id = "com.google.gms.google-services", version.ref = "google-service-version" }
chaquopy = { id = "com.chaquo.python", version.ref = "chaquopy-version" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-version" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }